import 'package:flutter/material.dart';

// This file is automatically generated by the Amplify CLI.
// Make sure the path is correct and the file exists.

import 'package:app_abejas/screens/home_screen.dart'; // Directamente a HomeScreen

Future<void> main() async {
  // This is required to ensure that plugin services are initialized before runApp()
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App Abejas',
      theme: ThemeData(
        primarySwatch: Colors.amber, // Using amber as per your previous context
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const HomeScreen(), // Directamente a HomeScreen
    );
  }
}
